config/routes.rb
Codemetrics::Application.routes.draw do

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :users

  resources :codes do
    collection do
      post "ajax_query"
      post "rubocop_stat"
    end
  end

  root to: "codes#index"

end

app/models/code.rb
class Code < ActiveRecord::Base

  self.per_page = 5

  validates :code_fmt, format: { with: /(rb|java|js|coffee)/,
    message: "upload file format error !!!" }
    
end

app/models/user.rb
require "fileutils"

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  # 
  after_save :create_and_update_user_directory

  # 
  after_destroy :ensure_an_admin_remains, :destroy_user_directory

  private
    
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end

    def create_and_update_user_directory
      FileUtils.mkdir_p Rails.root + "public/#{self.name}"
    end

    def destroy_user_directory
      FileUtils.rmtree Rails.root + "public/#{self.name}"
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #
  before_action :authorize 

  protected
    def authorize
      logger.info "request.format:" + request.format
      if request.format == Mime::HTML || request.format == Mime::JSON
        unless User.find_by(id: session[:user_id])
          redirect_to login_url, notice: "Please log in"
        end
      else
        authenticate_or_request_with_http_basic do |username, password|
          user = User.find_by(name: username)
          user && user.authenticate(password)
        end
      end
    end
end

app/controllers/codes_controller.rb
require "rouge"
require "code_statistics_calculator.rb"

class CodesController < ApplicationController
  
  def index

    @message = 'hello rails'
    logger.debug "query params:" + params.inspect

    if params[:code_name].nil?
      @codes = Code.all.paginate(:page => params[:page])
    else
      # TODO:sql injection ???
      @codes = Code.where("code_name like ?", '%' + params[:code_name].strip + '%').paginate(:page => params[:page])
    end

  end

  def new
    @code = Code.new
  end

  def show
    
    @code = Code.find(params[:id])
    # make some nice lexed html
    path = Rails.root + @code.code_path
    source = File.read(path)
    formatter = Rouge::Formatters::HTML.new({:css_class => 'highlight', :line_numbers => true, :wrap => true})
    lexer = Rouge::Lexers::Shell.new
    # @code_css = Rouge::Themes::ThankfulEyes.render(:scope => '.highlight')
    @code_content = formatter.format(lexer.lex(source))

    # 
    @stat = calculate_directory_statistics(path)
    logger.debug "Code stats:" + @stat.inspect

  end

  def create

    # @book = Book.new(params[:book].permit(:title, :sub_title, :author, :publish_date))
    # debugger
    # @code = Code.new(code_params)
    @code = Code.new

    # 
    upload_path = upload
    set_code_file_path(upload_path)

    logger.info "saveing..."
    if @code.save
      # debugger
      redirect_to @code
    else
      render 'new'
    end

  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy
    redirect_to codes_path
  end

  # TODO:refactor ???
  def ajax_query
    
    logger.info "params[:code_name]:" + params[:code_name]
    options = {}
    # 
    find_options = { 
          :conditions => [ "LOWER(codes.code_name) LIKE (?)", '%' + params[:code_name].downcase + '%' ], 
          :order => "codes.id ASC",
          :limit => 10 }.merge!(options)

    @ajax_codes = Code.find(:all, find_options)

    render json: @ajax_codes
  end

  # TODO: ajax to rubocop
  def rubocop_stat
    logger.info "params[:id]:" + params[:id]
    @code = Code.find(params[:id])

    # 
    if @code.code_fmt == 'rb'
      file_path = Rails.root.to_s + '/' + @code.code_path
      logger.info "code_path:" + @code.code_path
      logger.info "file path:" + file_path
      output = IO.popen('rubocop -f json ' + file_path) if File.exist?(file_path)
      # puts output.read
      json_fmt = output.read
      rubocop_info = JSON.parse(json_fmt)

      # set json data to code_analysis 
      # you can use rubocop_info.inspect to present the hash data...
      logger.info "json:" + rubocop_info.to_json
      @code.update(code_analysis: rubocop_info.to_json)
      
      render json: rubocop_info
    else
      logger.info "file fomrmat:" + @code.code_fmt
      render :json => {:format => @code.code_fmt}
    end

  end

  private
    def code_params
      # logger.info "upload code file name:" + params[:code][:code_file].to_s
      # params.require(:code).permit(:code_file)
    end

  private
    def upload
      logger.info "uploading file..." 
      uploaded_io = params[:code][:code_file]

      @code.code_name = uploaded_io.original_filename
      # @code.code_fmt = uploaded_io.original_filename.split(".")[1]
      @code.code_fmt = File.extname(uploaded_io.original_filename).sub(/\A\./, '').downcase

      # 單檔上傳
      if !uploaded_io.nil? && @code.valid?
        File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file| 
          file.write(uploaded_io.read)
        end
        logger.info "uploading file path:" + "public/uploads/" + uploaded_io.original_filename
        upload_path = "public/uploads/" + uploaded_io.original_filename
      end
    end

  private
    def set_code_file_path (upload_path)
      if upload_path.to_s.strip.length != 0
        @code.code_path = upload_path
      end
    end

  private
    def calculate_directory_statistics(path, pattern = /.*\.(rb|js|coffee|java)$/)
      stats = CodeStatisticsCalculator.new
      stats.add_by_file_path(path)
      stats
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorize
  
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
  def hello_world(name)
    "hello #{name}"
    content_tag(:div, "Hello #{name}!")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container">
  
  <h1>Admin#index</h1>
  <p>Find me in app/views/admin/index.html.erb</p>

  <p>It is <%= Time.now %></p>

  <p>User info:</p>
  <p>session:<%= session[:user_id] %></p> 
</div>

app/views/codes/_form.html.erb
<div class="row">
  <div class="col-md-12">
  <%= form_for @code, :html => {:class => '', 'role' => 'form'} do |f| %>
    <div class="input-group col-xs-4">
      <%#= f.label :code_file, 'code file upload', :class => '' %>
      <span class="input-group-addon"><span class="glyphicon glyphicon-cloud-upload"></span></span>
      <%= f.file_field :code_file, :class => 'form-control' %>
    </div>
    <p class="help-block">File format: rb, java, js, coffee.</p>

    <% if @code.errors.any? %>
      <div class="row">
        <div class="col-md-4">
          <div class="alert alert-danger alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <strong>Error!</strong> 
            <% @code.errors.full_messages.each do |msg| %>
              <%= msg %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <%= link_to 'Back to list', codes_path, :class => "btn btn-default", :role => "button" %> 

    <%= f.button '送交', :class => 'btn btn-primary' %>

  <% end %>
  </div>
</div>

app/views/codes/index.html.erb
<h1>Codes#index</h1>
<p>Find me in app/views/codes/index.html.erb</p>
<p><%= @message %></p>
<%= hello_world "tony" %>

<h1>Codes List</h1>

<style>
  th.info {
    width: 15%
  }
</style>

<script>
  $(function() {
    $( "#code_name" ).autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "/codes/ajax_query",
          type: "post",
          dataType: "json",
          data: {
            featureClass: "P",
            style: "full",
            maxRows: 5,
            code_name: request.term
          },
          success: function(data) {
            response( $.map( data, function( item ) {
              return {
                label: item.code_name,
                value: item.code_name
              }
            }));
          }
        });
      }
    });
  });
</script>

<%= form_tag("/codes", method: "get") do %>
<div class="ui-widget">
  <%= label_tag(:code_name, "File Name:") %>
  <%= text_field_tag(:code_name) %>
  <%= submit_tag("Search") %>
</div>
<% end %>

<br/>

<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>File Name</th>
        <th>File Path</th>
        <th>File Format</th>
        <th class="info">Info</th>
      </tr>
    </thead>
    <tbody>

      <% @codes.each_with_index do |code, index| %>
        <tr class="code_list">
          <td><%= index + 1 %></td>
          <td><%= code.code_name %></td>
          <td><%= code.code_path %></td>
          <td><%= code.code_fmt %></td>
          <td><%= link_to 'source code', code_path(code), :class => "btn btn-primary btn-sm active", :role => "button" %> 
                  | <%= link_to 'Delete', code_path(code),
                      method: :delete, data: { confirm: 'Are you sure?' },  
                      :class => "btn btn-danger btn-sm active", :role => "button" %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

<div class="pagination">
  <%= will_paginate @codes, :container => false %>
</div>

<div class="page_info">
  <%= page_entries_info @codes, :model => 'datas', :html => true %>
</div>

app/views/codes/new.html.erb
<h1>Codes metrics</h1>
<p>upload code</p>

<script>
  $(function(){

    $('#new_code').submit(function(){      
      var file = $('#code_code_file').val();
      if ($.trim(file) === '') {
        event.preventDefault();
        alert('plz upload file !!!');
      }
    });

  })
</script>

<%= render 'form' %>

app/views/codes/show.html.erb
<%= stylesheet_link_tag "codes", params[:codes] %>

<script>
  $(function(){

    // TODO: loading data plugin ???
    $('#rubocop').click(function(){

      // alert("OH YA !!!");
      $.ajax({
          url: "/codes/rubocop_stat",
          type: "post",
          dataType: "json",
          data: {
            id: '<%= @code.id %>'
          }
        }).done(function( data ) {
          // if ( console && console.log ) {
          //   console.log( "Sample of data:", data);
          // }
          if (data.format !== undefined) {
            alert("We can rubocop the java guys...");
          } else {
            showData(data)
          }
        });

    });

    var showData = function(json){
      
      var data = '';
      metadata = ' <h4>Ruby File Analysis:</h4> ' +
        ' <p class="text-left text-info">metadata:</p> ' +
        ' <dl class="dl-horizontal"> ' + 
        ' <dt>rubocop_version</dt> ' + 
        ' <dd>' + json["metadata"]["rubocop_version"] + '</dd> ' +
        ' <dt>ruby_engine</dt>' + 
        ' <dd>' + json["metadata"]["ruby_engine"] + '</dd>' +  
        ' <dt>ruby_version</dt>' + 
        ' <dd>' + json["metadata"]["ruby_version"] + '</dd>' +
        ' <dt>ruby_patchlevel</dt>' +  
        ' <dd>' + json["metadata"]["ruby_patchlevel"] + '</dd>' +
        ' <dt>ruby_platform</dt> ' +
        ' <dd>' + json["metadata"]["ruby_platform"] + '</dd>' +
        ' </dl> ';
      data += metadata;

      // <p class="text-left text-info">files:../../helloworld.rb</p>
      // alert(json["files"].length);

      for (var i = 0; i < json["files"].length; i++) {
        //
        mainData = "<p class=\"text-left text-info\">file path:" + json["files"][i]["path"] + "</p>";
        mainData += ' <p class="text-left text-info">offences:</p> ';
        for (var j = 0; j < json["files"][i]["offences"].length; j++) {
          mainData += 
            ' <dl class="dl-horizontal"> ' + 
            ' <dt>severity</dt> ' + 
            ' <dd>' + json["files"][i]["offences"][j]["severity"] + '</dd>' +
            ' <dt>message</dt> ' + 
            ' <dd>' + json["files"][i]["offences"][j]["message"] + '</dd>' + 
            ' <dt>cop_name</dt> ' + 
            ' <dd>' + json["files"][i]["offences"][j]["cop_name"] + '</dd>' + 
            ' <dt>corrected</dt> ' + 
            ' <dd>' + json["files"][i]["offences"][j]["corrected"] + '</dd>' + 
            ' <dt>location</dt>' + 
            ' <dd>' + 
            ' line:' + json["files"][i]["offences"][j]["location"]["line"] + 
            ' , colunm:' + json["files"][i]["offences"][j]["location"]["column"] + 
            ' </dd> ' + 
            ' </dl> ';
        };
        data += mainData;
      };

      // summary:\"summary\":{\"offence_count\":3,\"target_file_count\":1,\"inspected_file_count\":1}}"]
      summaryData =
        ' <p class="text-left text-info">summary:</p> ' +
        ' <dl class="dl-horizontal"> ' + 
        ' <dt>offence_count</dt> ' + 
        ' <dd>' + json["summary"]["offence_count"] + "</dd>" + 
        ' <dt>target_file_count</dt> ' +
        ' <dd>' + json["summary"]["target_file_count"] + "</dd>" + 
        ' <dt>inspected_file_count</dt>' + 
        ' <dd>' + json["summary"]["inspected_file_count"] +
        ' <dl>';
      data += summaryData;
      
      $('div.rubocop_data').empty().html(data);
    }

  });
</script>

<div class="container">
  <h1>File Info</h1>

  <dl class="dl-horizontal">
    <dt>Code Id</dt>
    <dd><%= @code.id %></dd>
    <dt>Code Path</dt>
    <dd><%= @code.code_path %></dd>
    <dt>Code File Name</dt>
    <dd><%= @code.code_name %></dd>
    <dt>Code File Format</dt>
    <dd><%= @code.code_fmt %></dd>
    
    <dt>Code lines</dt>
    <dd><%= @stat.lines %></dd>
    <dt>Code LOC</dt>
    <dd><%= @stat.code_lines %></dd>
    <dt>Code Classes</dt>
    <dd><%= @stat.classes %></dd>
    <dt>Code Methods</dt>
    <dd><%= @stat.methods %></dd>
  </dl>
  
  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-default" id="rubocop">Rubocop !!!</button>
      <div class="rubocop_data"></div>
      
      <%#
      <div class="xxx">
        <h4>Ruby File Analysis:</h4>
        <p class="text-left text-info">metadata:</p>
        <dl class="dl-horizontal">
          <dt>rubocop_version</dt>
          <dd>0.16.0</dd>
          <dt></dt>
          <dd></dd>
        </dl>
        <p class="text-left text-info">files:../../helloworld.rb</p>
        <p class="text-left text-info">offences:</p>
        <dl class="dl-horizontal">
          <dt>severity</dt>
          <dd>convention</dd>
          <dt>message</dt>
          <dd>refer single-quoted strings when you don't need string interpolation or special symbols.</dd>
          <dt>cop_name</dt>
          <dd>StringLiterals</dd>
          <dt>corrected</dt>
          <dd>nil</dd>
          <dt>location</dt>
          <dd>
            line:1, colunm:9 <br/>
            line:3, colunm:15
          </dd>
        </dl>
        <p class="text-left text-info">summary:</p>
        <dl class="dl-horizontal">
          <dt>offence_count</dt>
          <dd>3</dd>
        </dl>
      </div>
      %>
      
    </div>
  </div>

  <br/>

  <div class="row">
    <div class="col-md-12">
    <%= raw(@code_content) %>
    
    <br/>
    <button type="button" class="btn btn-default"><%= link_to 'Back to list', codes_path %></button>
    
    </div> 
  </div>
</div

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Code Metrics', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      
      <% if session[:user_id] %>      
        <%= button_to 'Logout', logout_path, :method => :delete, :class => "btn btn-default navbar-btn navbar-right" %>
      <% else %>
        <%= link_to 'Login', login_path, :class => "btn btn-default navbar-btn navbar-right" %>
      <% end  %>
    
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<script>
  $(function(){
    $( ".mousemove" )
      .mouseover(function() {
        // add class to the one we clicked
        $(this).addClass("active");
      })
      .mouseout(function() {
        //  
        $(this).removeClass("active");
      });
  });
</script>

<li class="mousemove">
  <%= link_to 'HOME', codes_path %>
</li>
<li class="mousemove">
  <%= link_to 'UPLOAD FILE', new_code_path %>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to 'User action', users_path %></li>
    <%#
    <li class="divider"></li>
    <li class="dropdown-header">Nav header</li>
    <li><a href="#">Separated link</a></li>
    <li><a href="#">One more separated link</a></li>
    %>
  </ul>
</li>

<%#
<li><a href="#contact">Contact</a></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li class="divider"></li>
    <li class="dropdown-header">Nav header</li>
    <li><a href="#">Separated link</a></li>
    <li><a href="#">One more separated link</a></li>
  </ul>
</li>
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Codemetrics" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Codemetrics" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller.controller_name%>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <h1>Listing users</h1>
  <div class="table-responsive">
    <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Password digest</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        <% @users.each_with_index do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.password_digest %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
  
  <%= link_to 'New User', new_user_path %>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>